config/routes.rb
Rails.application.routes.draw do
  
  get 'seriens/new'
  resources :seriens

  get 'mangas/new'
  resources :mangas

  get 'animes/new'
  resources :animes
    
  root 'welcome#index'
  

end

app/models/anime.rb
class Anime < ActiveRecord::Base
end

app/models/manga.rb
class Manga < ActiveRecord::Base
end

app/models/serien.rb
class Serien < ActiveRecord::Base
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  def new
  end
  
  def edit
    @anime = Anime.find(params[:id])
  end
  
  def update
    @anime = Anime.find(params[:id])
   
    if @anime.update(anime_params)
      redirect_to root_path, notice: "Anime updated"
    else
      flash[:error] = "Somethig is wrong"
    end
  end
  
  def create
    @anime = Anime.new(anime_params)
     
    @anime.save
    redirect_to root_path, notice: "New Anime created"
  end
  
  def destroy
    @anime = Anime.find(params[:id])
    @anime.destroy
    
    redirect_to root_path, notice: "Anime deleted"
  end
  
  
  private
    def anime_params
      params.require(:anime).permit(:title, :episode, :release, :url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  def new
    end
    
    def edit
      @manga = Manga.find(params[:id])
    end
    
    def update
      @manga = Manga.find(params[:id])
     
      if @manga.update(manga_params)
        redirect_to root_path, notice: "Manga updated"
      else
        flash[:error] = "Somethig is wrong"
      end
    end
    
    def create
      @manga = Manga.new(manga_params)
       
      @manga.save
      redirect_to root_path, notice: "New Manga created"
    end
    
    def destroy
      @manga = Manga.find(params[:id])
      @manga.destroy
      
      redirect_to root_path, notice: "Manga deleted"
    end
    
    
    private
      def manga_params
        params.require(:manga).permit(:title, :chapter, :release, :url)
      end
end

app/controllers/seriens_controller.rb
class SeriensController < ApplicationController
  def index
      @seriens = Serien.all
    end
  
  def new
  end
  
  def edit
    @serien = Serien.find(params[:id])
  end
  
  def update
    @serien = Serien.find(params[:id])
   
    if @serien.update(serien_params)
      redirect_to root_path, notice: "Series updated"
    else
      flash[:error] = "Somethig is wrong"
    end
  end
  
  def create
    @serien = Serien.new(serien_params)
     
    @serien.save
    redirect_to root_path, notice: "New Series created"
  end
  
  def destroy
    @serien = Serien.find(params[:id])
    @serien.destroy
    
    redirect_to root_path, notice: "Series deleted"
  end
  
  
  private
    def serien_params
      params.require(:serien).permit(:title, :episode, :release, :url, :archiveFlag)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @animes = Anime.all
    @mangas = Manga.all
    @seriens = Serien.all
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/helpers/seriens_helper.rb
module SeriensHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/animes/edit.html.erb
</br>
<div class="row">
  	<h1>Edit Anime</h1>
  	</br> </br>
<%= form_for :anime, url: anime_path(@anime), method: :patch do |f| %>
 
  <% if @anime.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@anime.errors.count, "error") %> prohibited
        this Anime from being saved:
      </h2>
      <ul>
        <% @anime.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
			<p>
		    	<%= f.text_field :title, :class => "form-control", :placeholder => "Titel" %>
		  	</p>
 
			<p>
			    <%= f.text_field :episode, :class => "form-control", :placeholder => "Episode Number" %>
			</p>
			
			<p>
			    <%= f.text_field :release, :class => "form-control", :placeholder => "Release Day" %>
			</p>
			<p>
			    <%= f.text_field :url, :class => "form-control", :placeholder => "GoGoAnime URL" %>
			</p>
 
  <p>
    <%= f.submit "Save", :class => "btn btn-primary" %>
    <%= link_to 'Back', root_path, :class => "btn btn-default" %>
  </p>
 
<% end %>
</div>

app/views/animes/new.html.erb
</br>
<div class="row">

  	<h1>New Anime</h1>
  	</br> </br>
  		<%= form_for :anime, url: animes_path do |f| %>
			<p>
		    	<%= f.text_field :title, :class => "form-control", :placeholder => "Titel" %>
		  	</p>
 
			<p>
			    <%= f.text_field :episode, :class => "form-control", :placeholder => "Episode Number" %>
			</p>
			
			<p>
			    <%= f.text_field :release, :class => "form-control", :placeholder => "Release Day" %>
			</p>
			<p>
			    <%= f.text_field :url, :class => "form-control", :placeholder => "GoGoAnime URL" %>
			</p>
 	
  			<p>
  				<%= f.submit "Save", :class => "btn btn-primary" %>
  				<%= link_to 'Back', root_path, :class => "btn btn-default" %>
  			</p>
		<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EpisodeChecker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
    </br>
      <%= yield %>
     </br>
    </div>

</body>
</html>

app/views/mangas/edit.html.erb
</br>
<div class="row">
  	<h1>Edit Manga</h1>
  	</br> </br>
<%= form_for :manga, url: manga_path(@manga), method: :patch do |f| %>
 
  <% if @manga.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@manga.errors.count, "error") %> prohibited
        this Manga from being saved:
      </h2>
      <ul>
        <% @manga.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
			<p>
		    	<%= f.text_field :title, :class => "form-control", :placeholder => "Titel" %>
		  	</p>
 
			<p>
			    <%= f.text_field :chapter, :class => "form-control", :placeholder => "Episode Number" %>
			</p>
			
			<p>
			    <%= f.text_field :release, :class => "form-control", :placeholder => "Release Day" %>
			</p>
			
			<p>
			    <%= f.text_field :url, :class => "form-control", :placeholder => "Mangapanda URL" %>
			</p>
 
  <p>
    <%= f.submit "Save", :class => "btn btn-primary" %>
    <%= link_to 'Back', root_path, :class => "btn btn-default" %>
  </p>
 
<% end %>
</div>

app/views/mangas/new.html.erb
</br>
<div class="row">

  	<h1>New Manga</h1>
  	</br> </br>
  		<%= form_for :manga, url: mangas_path do |f| %>
			<p>
		    	<%= f.text_field :title, :class => "form-control", :placeholder => "Titel" %>
		  	</p>
 
			<p>
			    <%= f.text_field :chapter, :class => "form-control", :placeholder => "Episode Number" %>
			</p>
			
			<p>
			    <%= f.text_field :release, :class => "form-control", :placeholder => "Release Day" %>
			</p>
			
			<p>
			    <%= f.text_field :url, :class => "form-control", :placeholder => "Mangapanda URL" %>
			</p>
 	
  			<p>
  				<%= f.submit "Save", :class => "btn btn-primary" %>
  				<%= link_to 'Back', root_path, :class => "btn btn-default" %>
  			</p>
		<% end %>
</div>

app/views/seriens/edit.html.erb
</br>
<div class="row">
  	<h1>Edit Series</h1>
  	</br> </br>
<%= form_for :serien, url: serien_path(@serien), method: :patch do |f| %>
 
  <% if @serien.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@serien.errors.count, "error") %> prohibited
        this Serien from being saved:
      </h2>
      <ul>
        <% @serien.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
			<p>
		    	<%= f.text_field :title, :class => "form-control", :placeholder => "Titel with Season" %>
		  	</p>
 
			<p>
			    <%= f.text_field :episode, :class => "form-control", :placeholder => "Episode Number" %>
			</p>
			
			<p>
			    <%= f.text_field :release, :class => "form-control", :placeholder => "Release Day" %>
			</p>
			<p>
			    <%= f.text_field :url, :class => "form-control", :placeholder => "LoadTV URL" %>
			</p>
			</p>
 				Archiviert? <%= f.check_box :archiveFlag %>
  			<p>
 
  <p>
    <%= f.submit "Save", :class => "btn btn-primary" %>
    <%= link_to 'Back', root_path, :class => "btn btn-default" %>
  </p>
 
<% end %>
</div>

app/views/seriens/index.html.erb
	<h2>Series</h2>
  		<div class="table-responsive">
  			<table class="table">
  			<tbody>
  				<tr>
  					<th>#</th>
  					<th>Titel</th>
  					<th>Last seen Episode</th>
  					<th>Newest Chapter</th>
  					<th>Release</th>
  					<th>Watched</th>
  					<th>Open</th>
  					<th>Edit</th>
  					<th>Delete</th>
  				</tr>
  				
  				<% @seriens.each do |serien| %>
  					<%
    					require 'rubygems'
    					require 'nokogiri'
    					require 'open-uri'
       					doc = Nokogiri::HTML(open(serien.url))
    					lastEpisode = doc.at_css("p span strong").text[/[0-9]+/]
    				%>
    				
    				<% if serien.episode <= lastEpisode.to_i - 1 %>
  						<tr bgcolor="#ffffb2">
  					<% elsif serien.archiveFlag == true %>
  						<tr bgcolor="#FF9966">
  					<% elsif serien.episode == lastEpisode.to_i %>
  						<tr>
  					<% else %>
  						<tr bgcolor="#ffb2b2">
  					<% end %>
  						<td><%= serien.id %></td>
      					<td><%= serien.title %></td>
      					<td><%= serien.episode %></td>
      					<td><%= lastEpisode %></td>
      					<td><%= serien.release %></td>
      					<td>
   							<%= form_for serien do |t| %>
     							<%= t.hidden_field :episode, :value=>serien.episode+1 %>
    							<%= t.submit "Watched", :class => "btn btn-primary" %>
   							<% end %>
      					</td>
      					<td>
      						<a class="btn btn-primary" target="_blank" href="<%= serien.url %>" role="button">Open</a>
      					</td>
      					<td>
							<a class="btn btn-primary" href="/seriens/<%= serien.id %>/edit" role="button">Edit</a>
      					</td>
      					<td>
      						<%= link_to 'Delete', serien_path(serien), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
              			</td>
    				</tr>
  				<% end %>
  			</tbody>
			</table>
			<a class="btn btn-primary" href="/seriens/new" role="button">Add new Series</a> </br> </br>
			<%= link_to 'Back', root_path, :class => "btn btn-default" %>
		</div>

app/views/seriens/new.html.erb
</br>
<div class="row">

  	<h1>New Series</h1>
  	</br> </br>
  		<%= form_for :serien, url: seriens_path do |f| %>
			<p>
		    	<%= f.text_field :title, :class => "form-control", :placeholder => "Titel with Season" %>
		  	</p>
 
			<p>
			    <%= f.text_field :episode, :class => "form-control", :placeholder => "Episode Number" %>
			</p>
			
			<p>
			    <%= f.text_field :release, :class => "form-control", :placeholder => "Release Day" %>
			</p>
			<p>
			    <%= f.text_field :url, :class => "form-control", :placeholder => "LoadTV URL" %>
			</p>
 				Archiviert? <%= f.check_box :archiveFlag %>
  			<p>
  				<%= f.submit "Save", :class => "btn btn-primary" %>
  				<%= link_to 'Back', root_path, :class => "btn btn-default" %>
  			</p>
		<% end %>
</div>

app/views/welcome/index.html - Kopie.erb
  	<h1>Episode Checker</h1> </br></br>
  		<% if flash[:notice] %>
		    <% flash.each do |name, msg| %>
 				<% if msg.is_a?(String) %>
 				    <script type="text/javascript">	
 						$.notify({
							message: '<%= msg %>',
							target: '_blank'
						}, {
							type: "info"
						});
					</script> 
				<% end %>
			<% end %>
    	<% end %>

    	<h2>Misc</h2>
  		</br>
  	  	<h2>Series</h2>
  		<div class="table-responsive">
  			<table class="table">
  			<tbody>
  				<tr>
  					<th>#</th>
  					<th>Titel</th>
  					<th>Last seen Episode</th>
  					<th>Newest Chapter</th>
  					<th>Release</th>
  					<th>Watched</th>
  					<th>Open</th>
  					<th>Edit</th>
  					<th>Delete</th>
  				</tr>
  				
  				<% @seriens.each do |serien| %>
  				<% if serien.archiveFlag == false %>
  					<%
    					require 'rubygems'
    					require 'nokogiri'
    					require 'open-uri'
       					doc = Nokogiri::HTML(open(serien.url))
    					lastEpisode = doc.at_css("p span strong").text[/[0-9]+/]
    				%>
    				
    				<% if serien.episode <= lastEpisode.to_i - 1 %>
  						<tr bgcolor="#ffffb2">
  					<% elsif serien.episode == lastEpisode.to_i %>
  						<tr>
  					<% else %>
  						<tr bgcolor="#ffb2b2">
  					<% end %>
  						<td><%= serien.id %></td>
      					<td><%= serien.title %></td>
      					<td><%= serien.episode %></td>
      					<td><%= lastEpisode %></td>
      					<td><%= serien.release %></td>
      					<td>
   							<%= form_for serien do |t| %>
     							<%= t.hidden_field :episode, :value=>serien.episode+1 %>
    							<%= t.submit "Watched", :class => "btn btn-primary" %>
   							<% end %>
      					</td>
      					<td>
      						<a class="btn btn-primary" target="_blank" href="<%= serien.url %>" role="button">Open</a>
      					</td>
      					<td>
							<a class="btn btn-primary" href="/seriens/<%= serien.id %>/edit" role="button">Edit</a>
      					</td>
      					<td>
      						<%= link_to 'Delete', serien_path(serien), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
              			</td>
    				</tr>
    			<% end %>
  				<% end %>
  			</tbody>
			</table>
			<a class="btn btn-primary" href="/seriens/new" role="button">Add new Series</a> </br> </br>
			<a class="btn btn-primary" href="/seriens" role="button">Show All</a>
		</div>
  	</br>
  	<h2>Animes</h2>
  		<div class="table-responsive">
  			<table class="table">
  			<tbody>
  				<tr>
  					<th>#</th>
  					<th>Titel</th>
  					<th>Last seen Episode</th>
  					<th>Newest Chapter</th>
  					<th>Release</th>
  					<th>Watched</th>
  					<th>Open</th>
  					<th>Edit</th>
  					<th>Delete</th>
  				</tr>
  				
  				<% @animes.each do |anime| %>
  					<%
      					require 'rubygems'
    					require 'nokogiri'
    					require 'open-uri'
    
						<% if false %>
						doc = Nokogiri::HTML(open(anime.url))
    					lastEpisode = doc.at_css(".active").attr("ep_end")
						<% end %>
						lastEpisode = 999
    				%>
    				
  					<% if anime.episode <= lastEpisode.to_i - 1 %>
  						<tr bgcolor="#ffffb2">
  					<% elsif anime.episode == lastEpisode.to_i %>
  						<tr>
  					<% else %>
  						<tr bgcolor="#ffb2b2">
  					<% end %>
  						<td><%= anime.id %></td>
      					<td><%= anime.title %></td>
      					<td><%= anime.episode %></td>
      					<td><%= lastEpisode %></td>
      					<td><%= anime.release %></td>
      					<td>
   							<%= form_for anime do |t| %>
     							<%= t.hidden_field :episode, :value=>anime.episode+1 %>
    							<%= t.submit "Watched", :class => "btn btn-primary" %>
   							<% end %>
      					</td>
      					<td>
      						<a class="btn btn-primary" target="_blank" href="<%= anime.url %>" role="button">Open</a>
      					</td>
      					<td>
							<a class="btn btn-primary" href="/animes/<%= anime.id %>/edit" role="button">Edit</a>
      					</td>
      					<td>
      						<%= link_to 'Delete', anime_path(anime), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
              			</td>
    				</tr>
  				<% end %>
  			</tbody>
			</table>
			<a class="btn btn-primary" href="/animes/new" role="button">Add new Anime</a>
		</div>
  	</br>
  	<h2>Mangas</h2>
  		<div class="table-responsive">
  			<table class="table">
  			<tbody>
  				<tr>
  					<th>#</th>
  					<th>Titel</th>
  					<th>Last seen Chapter</th>
  					<th>Newest Chapter</th>
  					<th>Release</th>
  					<th>Watched</th>
  					<th>Open</th>
  					<th>Edit</th>
  					<th>Delete</th>
  				</tr>
  				
  				<% @mangas.each do |manga| %>
  					<%
   						require 'rubygems'
   						require 'nokogiri'
   						require 'open-uri'
    
    					doc = Nokogiri::HTML(open(manga.url))
    					lastChapter = doc.at_css("#latestchapters li:nth-child(1) a").text[/[0-9\.]+/]
    				%>
  				
  					<% if manga.chapter <= lastChapter.to_i - 1 %>
  						<tr bgcolor="#ffffb2">
  					<% elsif manga.chapter == lastChapter.to_i %>
  						<tr>
  					<% else %>
  						<tr bgcolor="#ffb2b2">
  					<% end %>
  						<td><%= manga.id %></td>
      					<td><%= manga.title %></td>
      					<td><%= manga.chapter %></td>
      					<td><%= lastChapter %></td>
      					<td><%= manga.release %></td>
      					<td>
   							<%= form_for manga do |t| %>
     							<%= t.hidden_field :chapter, :value=>manga.chapter+1 %>
    							<%= t.submit "Watched", :class => "btn btn-primary" %>
   							<% end %>
      					</td>
      					<td>
      						<a class="btn btn-primary" target="_blank" href="<%= manga.url %>" role="button">Open</a>
      					</td>
      					<td>
							<a class="btn btn-primary" href="/mangas/<%= manga.id %>/edit" role="button">Edit</a>
      					</td>
      					<td>
      						<%= link_to 'Delete', manga_path(manga), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
              			</td>
    				</tr>
  				<% end %>
  			</tbody>
			</table>
			<a class="btn btn-primary" href="/mangas/new" role="button">Add new Manga</a>
		</div>

app/views/welcome/index.html.erb
  	<h1>Episode Checker</h1> </br></br>
  		<% if flash[:notice] %>
		    <% flash.each do |name, msg| %>
 				<% if msg.is_a?(String) %>
 				    <script type="text/javascript">	
 						$.notify({
							message: '<%= msg %>',
							target: '_blank'
						}, {
							type: "info"
						});
					</script> 
				<% end %>
			<% end %>
    	<% end %>

    	<h2>Misc</h2>
  		</br>
  	  	<h2>Series</h2>
  		<div class="table-responsive">
  			<table class="table">
  			<tbody>
  				<tr>
  					<th>#</th>
  					<th>Titel</th>
  					<th>Last seen Episode</th>
  					<th>Newest Chapter</th>
  					<th>Release</th>
  					<th>Watched</th>
  					<th>Open</th>
  					<th>Edit</th>
  					<th>Delete</th>
  				</tr>
  				
  				<% @seriens.each do |serien| %>
  				<% if serien.archiveFlag == false %>
  					<% if false %>
  						<%
    						require 'rubygems'
    						require 'nokogiri'
    						require 'open-uri'
       						doc = Nokogiri::HTML(open(serien.url))
    						lastEpisode = doc.at_css("p span strong").text[/[0-9]+/]
    					%>
    				<% end %>
    				<% lastEpisode = 999 %>
    				<% if serien.episode <= lastEpisode.to_i - 1 %>
  						<tr bgcolor="#ffffb2">
  					<% elsif serien.episode == lastEpisode.to_i %>
  						<tr>
  					<% else %>
  						<tr bgcolor="#ffb2b2">
  					<% end %>
  						<td><%= serien.id %></td>
      					<td><%= serien.title %></td>
      					<td><%= serien.episode %></td>
      					<td><%= lastEpisode %></td>
      					<td><%= serien.release %></td>
      					<td>
   							<%= form_for serien do |t| %>
     							<%= t.hidden_field :episode, :value=>serien.episode+1 %>
    							<%= t.submit "Watched", :class => "btn btn-primary" %>
   							<% end %>
      					</td>
      					<td>
      						<a class="btn btn-primary" target="_blank" href="<%= serien.url %>" role="button">Open</a>
      					</td>
      					<td>
							<a class="btn btn-primary" href="/seriens/<%= serien.id %>/edit" role="button">Edit</a>
      					</td>
      					<td>
      						<%= link_to 'Delete', serien_path(serien), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
              			</td>
    				</tr>
    			<% end %>
  				<% end %>
  			</tbody>
			</table>
			<a class="btn btn-primary" href="/seriens/new" role="button">Add new Series</a> </br> </br>
			<a class="btn btn-primary" href="/seriens" role="button">Show All</a>
		</div>
  	</br>
  	<h2>Animes</h2>
  		<div class="table-responsive">
  			<table class="table">
  			<tbody>
  				<tr>
  					<th>#</th>
  					<th>Titel</th>
  					<th>Last seen Episode</th>
  					<th>Newest Chapter</th>
  					<th>Release</th>
  					<th>Watched</th>
  					<th>Open</th>
  					<th>Edit</th>
  					<th>Delete</th>
  				</tr>
  				
  				<% @animes.each do |anime| %>
  					<%
      					require 'rubygems'
    					require 'nokogiri'
    					require 'open-uri'
    
						lastEpisode = 999
    				%>
    				
  					<% if anime.episode <= lastEpisode.to_i - 1 %>
  						<tr bgcolor="#ffffb2">
  					<% elsif anime.episode == lastEpisode.to_i %>
  						<tr>
  					<% else %>
  						<tr bgcolor="#ffb2b2">
  					<% end %>
  						<td><%= anime.id %></td>
      					<td><%= anime.title %></td>
      					<td><%= anime.episode %></td>
      					<td><%= lastEpisode %></td>
      					<td><%= anime.release %></td>
      					<td>
   							<%= form_for anime do |t| %>
     							<%= t.hidden_field :episode, :value=>anime.episode+1 %>
    							<%= t.submit "Watched", :class => "btn btn-primary" %>
   							<% end %>
      					</td>
      					<td>
      						<a class="btn btn-primary" target="_blank" href="<%= anime.url %>" role="button">Open</a>
      					</td>
      					<td>
							<a class="btn btn-primary" href="/animes/<%= anime.id %>/edit" role="button">Edit</a>
      					</td>
      					<td>
      						<%= link_to 'Delete', anime_path(anime), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
              			</td>
    				</tr>
  				<% end %>
  			</tbody>
			</table>
			<a class="btn btn-primary" href="/animes/new" role="button">Add new Anime</a>
		</div>
  	</br>
  	<h2>Mangas</h2>
  		<div class="table-responsive">
  			<table class="table">
  			<tbody>
  				<tr>
  					<th>#</th>
  					<th>Titel</th>
  					<th>Last seen Chapter</th>
  					<th>Newest Chapter</th>
  					<th>Release</th>
  					<th>Watched</th>
  					<th>Open</th>
  					<th>Edit</th>
  					<th>Delete</th>
  				</tr>
  				
  				<% @mangas.each do |manga| %>
  					<%
   						require 'rubygems'
   						require 'nokogiri'
   						require 'open-uri'
    
    					doc = Nokogiri::HTML(open(manga.url))
    					lastChapter = doc.at_css("#latestchapters li:nth-child(1) a").text[/[0-9\.]+/]
    				%>
  				
  					<% if manga.chapter <= lastChapter.to_i - 1 %>
  						<tr bgcolor="#ffffb2">
  					<% elsif manga.chapter == lastChapter.to_i %>
  						<tr>
  					<% else %>
  						<tr bgcolor="#ffb2b2">
  					<% end %>
  						<td><%= manga.id %></td>
      					<td><%= manga.title %></td>
      					<td><%= manga.chapter %></td>
      					<td><%= lastChapter %></td>
      					<td><%= manga.release %></td>
      					<td>
   							<%= form_for manga do |t| %>
     							<%= t.hidden_field :chapter, :value=>manga.chapter+1 %>
    							<%= t.submit "Watched", :class => "btn btn-primary" %>
   							<% end %>
      					</td>
      					<td>
      						<a class="btn btn-primary" target="_blank" href="<%= manga.url %>" role="button">Open</a>
      					</td>
      					<td>
							<a class="btn btn-primary" href="/mangas/<%= manga.id %>/edit" role="button">Edit</a>
      					</td>
      					<td>
      						<%= link_to 'Delete', manga_path(manga), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
              			</td>
    				</tr>
  				<% end %>
  			</tbody>
			</table>
			<a class="btn btn-primary" href="/mangas/new" role="button">Add new Manga</a>
		</div>